#!groovy
////
pipeline {
    agent { label 'master' }
    environment {
        APP_NAME="HolaGordis-FAQ"
        PROJECT="Gordis-Jenkins-Yankees-intramundo"
        RELEASE_APP_NAME="HolaGordis-faq-release"
    }
    stages {
        stage ('Hace Checkout from GIT a SCM') {
            steps {
                checkout scm  
				echo " aqui hago el checkout para ubicarme en la branch conLogin"
            }
		}
        stage ('Setup CorteIngles/CentroDepot Environment') {
            steps {
                echo "branch name is ${env.JENKINS_HOME}"
                echo "branch name is ${env.BUILD_TAG}"
//                echo "branch name is" // ${env.BRANCH_NAME}"
//              script {
//                   if (env.BRANCH_NAME != "develop") {    //use this condition for Jenkins Version 2.107+
//                      hlSetEnv('IMAGE_TAG', hlCreateTagName('pkg:version'))
//                      hlSetEnv('APP_NAME', RELEASE_APP_NAME)
//                      hlSetEnv('SPRING_CONFIG_LABEL', 'master')
//                      echo "Perico Image Tag is ${IMAGE_TAG}"
//                  } else {
//                      hlSetEnv('IMAGE_TAG', 'latest')
//                      hlSetEnv('APP_NAME', APP_NAME)
//                      hlSetEnv('SPRING_CONFIG_LABEL', 'master')
//                      echo "Otro perico Image Tag is ${IMAGE_TAG}"
//                  }
//              }
           }
        }
    }
//
    post {
        always {
            cleanWs()
            echo ('echo "Todos los stages terminaron de ejecutarse. Barbaro!"')
        }
        success {
            echo("echo 'El Job termino de forma macheterica'")
        }
//        failure {
//			echo ("echo 'Mando el email con el error'")
//           emailext(
//                   to: 'joseluis.gonzalez@santander.co.uk',
//                   subject: "Jenkins File Fallo que Vaina: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
//                   body: "<a href='${env.BUILD_URL}'>Arreglame Mijitoco!</a>",
//                   recipientProviders: [[$class: 'DevelopersRecipientProvider'],
//                                        [$class: 'CulpritsRecipientProvider'],
//                                        [$class: 'RequesterRecipientProvider'],
//                                        [$class: 'FirstFailingBuildSuspectsRecipientProvider']]
//            )
//        }
    }
}
